graphql:
  packages:
    - "com.example.demo"
  automaticPersistedQueries:
    enabled: true
  batching:
    enabled: true
    strategy: SYNC_EXHAUSTION
  federation:
    enabled: true
    opt-in-v2: true
